services:
    bar.hi_command:
        class: BarBundle\Command\HiCommand
        tags:
            - { name: console.command }
#            - { name: chaincommand.chained, chainto: foo.hello_command }