services:
    ccc.command.foo:
        class: ChainCommandBundle\Command\FooCommand
        tags:
            - { name: console.command }
    ccc.command.bar:
        class: ChainCommandBundle\Command\BarCommand
        tags:
            - { name: console.command }
            - { name: chaincommand.chained, chainto: foo.hello_command }